<?php

namespace App\Http\Controllers\API;

use App\Http\Resources\ProductResources;
use App\Models\API\ProductModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-01 15:22:13
 * zip name 20220401152117_CpAJr2y0irM.zip
 */

class ProductController extends BaseController
{
    /*
    {
        "name" : "",
        "trans_date" : "",
        "volume" : ""
    }
    */
    //localhost:8000/api/product/insert
    public function insert(Request $r)
    {
        try {
            $input = array(
                'name' => 'required|string|min:1',
                'trans_date' => 'required|string|min:1',
                'volume' => 'required|string|min:1'
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $result = new ProductModel();
            $result->name = $r->name;
            $result->trans_date = $r->trans_date;
            $result->volume = $r->volume;
            $result->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/product/all
    public function all()
    {
        try {
            $result = ProductModel::all();

            return $this->toList(ProductResources::collection($result), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }


    //http://localhost:8000/api/product/paging?limit=10&page=1&start_date=2023-01-01&end_date=2023-01-01
    public function paging(Request $r)
    {
        try {
            $limit = $r->limit ? $r->limit : 10;
            $page = $r->page ? $r->page : 1;
            $start_date = $r->start_date;
            $end_date = $r->end_date;

            $query = DB::table('product_paging');

            if ($start_date) {
                $query = $query->whereDate('created_at', '>=', $start_date)
                    ->whereDate('created_at', '<=', $end_date);
            }

            $dataParsing = $query;

            return $this->toPaging(
                1,
                $dataParsing,
                $limit,
                $page
            );
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    /*
    {
        "name" : "",
        "trans_date" : "",
        "volume" : ""
    }
    */
    //localhost:8000/api/product/update/
    public function update(Request $r, $id)
    {
        try {
            $input = array(
                'name' => 'required|string|min:1',
                'trans_date' => 'required|string|min:1',
                'volume' => 'required|string|min:1'
            );

            $validator = Validator::make($r->all(), $input);

            if ($validator->fails()) {
                $apiResponse = $this->getApiResponse(0);
                $apiResponse->message = $validator->getMessageBag();
                return $this->responseFailed($apiResponse);
            }

            DB::beginTransaction();

            $result = ProductModel::find($id);
            $result->name = $r->name;
            $result->trans_date = $r->trans_date;
            $result->volume = $r->volume;
            $result->save();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            DB::rollBack();
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/product/delete/
    public function delete($id)
    {
        try {
            $result = ProductModel::find($id);

            DB::beginTransaction();

            $result->delete();

            DB::commit();

            $apiResponse = $this->getApiResponse(1);
            return $this->responseSuccess($apiResponse);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }

    //localhost:8000/api/product/find/
    public function find($id)
    {
        try {
            $result = ProductModel::find($id);

            return $this->toObject(new ProductResources($result), 1, 0);
        } catch (\Throwable $th) {
            return $this->responseError($th);
        }
    }
}
