<?php

namespace App\Http\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-01 15:22:14
 * zip name 20220401152117_CpAJr2y0irM.zip
 */

class ProductResources extends JsonResource
{
    /**
     *   new ProductResources(object)
     *   ProductResources::collection([])
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'trans_date' => $this->trans_date,
            'volume' => $this->volume,
            //'created_at' => Carbon::parse($this->created_at)->format('Y-m-d H:i:s'),
            //'updated_at' => Carbon::parse($this->updated_at)->format('Y-m-d H:i:s'),
        ];
    }
}
