<?php

namespace App\Models\API;

use App\MyApp;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-01 15:22:12
 * zip name 20220401152117_CpAJr2y0irM.zip
 */

class ProductModel extends Model
{
    use HasFactory;
    protected $table = "product";
    protected $fillable = ["name", "trans_date", "volume"];
    protected $casts = MyApp::datetime;

    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->belongsTo(OtherTable::class, 'id_in_ProductModel', 'id_in_other_table');
    //}

    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->hasMany(OtherTable::class, 'id_in_other_table', 'id_in_ProductModel');
    //}

    //ClassModel::with('other_table')->get();
    //public function other_table(){
    //    return $this->hasOne(OtherTable::class, 'id_in_other_table', 'id_in_ProductModel');
    //}
}
