<?php

namespace App;

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-04-01 15:18:28
 * zip name 20220401151709_K8U7cXP2NnI.zip
 */

class MyApp {
    const datetime = [
        'created_at'  => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
}

/*
//app
//config/app.php -> this file

'aliases' => [
  //...
  'MyApp' => AppMyApp::class,
*/